# Generated by Django 6.0.6 on 2026-09-09 04:00

import apps.mensajeria.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=20, unique=True)),
                ('origen_sistema', models.CharField(max_length=60)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Baja',
                'verbose_name_plural': 'Bajas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SistemaSuscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('api_key', models.CharField(max_length=100, unique=True)),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_hmac_secret', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sistema suscrito',
                'verbose_name_plural': 'Sistemas suscritos',
            },
        ),
        migrations.CreateModel(
            name='UltimaInteraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=20, unique=True)),
                ('ultimo_mensaje_entrante_en', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envio_id', models.CharField(default=apps.mensajeria.models._generar_envio_id, editable=False, max_length=40, unique=True)),
                ('destinatario', models.CharField(help_text='Número en formato E.164, ya normalizado.', max_length=20)),
                ('plantilla', models.CharField(max_length=100)),
                ('idioma', models.CharField(default='es_MX', max_length=10)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('adjunto', models.JSONField(blank=True, null=True)),
                ('enviar_despues_de', models.DateTimeField(blank=True, null=True)),
                ('origen_sistema', models.CharField(max_length=60)),
                ('origen_entidad', models.CharField(max_length=60)),
                ('origen_id', models.CharField(max_length=60)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('encolado', 'Encolado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('leido', 'Leído'), ('fallido', 'Fallido'), ('bloqueado', 'Bloqueado'), ('cancelado', 'Cancelado')], default='encolado', max_length=12)),
                ('motivo_bloqueo', models.CharField(blank=True, max_length=30)),
                ('wa_message_id', models.CharField(blank=True, max_length=100)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('huella_payload', models.CharField(max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('entregado_en', models.DateTimeField(blank=True, null=True)),
                ('leido_en', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['destinatario'], name='mensajeria__destina_4cc896_idx'), models.Index(fields=['origen_sistema', 'origen_entidad', 'origen_id'], name='mensajeria__origen__d79254_idx'), models.Index(fields=['content_type', 'object_id'], name='mensajeria__content_8138e4_idx')],
            },
        ),
    ]
