from django.urls import path

from . import views, views_entrevista_1a1, views_extra


app_name = 'certificacion_intera'

urlpatterns = [
    path(
        '',
        views.dashboard_view,
        name='dashboard',
    ),
    path(
        'procesos/',
        views.procesos_view,
        name='procesos',
    ),
    path(
        'participantes/',
        views.participantes_view,
        name='participantes',
    ),
    path(
        'entrevistas/',
        views.entrevistas_view,
        name='entrevistas',
    ),
    path(
        'seguimiento/',
        views.seguimiento_view,
        name='seguimiento',
    ),
    path(
        'configuracion/',
        views.configuracion_general_view,
        name='configuracion_general',
    ),
    path(
        'escuelas/',
        views.escuelas_view,
        name='escuelas',
    ),
    path(
        'escuelas/nueva/',
        views.escuela_crear_view,
        name='escuela_crear',
    ),
    path(
        'escuelas/nueva/confirmar/',
        views.escuela_confirmar_view,
        name='escuela_confirmar',
    ),
    path(
        'escuelas/<int:escuela_id>/',
        views.escuela_detalle_view,
        name='escuela_detalle',
    ),
    path(
        'escuelas/<int:escuela_id>/editar/',
        views.escuela_editar_view,
        name='escuela_editar',
    ),
    path(
        'procesos/nuevo/',
        views.proceso_crear_view,
        name='proceso_crear_general',
    ),
    path(
        'escuelas/<int:escuela_id>/procesos/nuevo/',
        views.proceso_crear_view,
        name='proceso_crear',
    ),
    path(
        'procesos/<int:proceso_id>/',
        views.proceso_detalle_view,
        name='proceso_detalle',
    ),
    path(
        'procesos/<int:proceso_id>/cerrar/',
        views.proceso_cerrar_view,
        name='proceso_cerrar',
    ),
    path(
        'procesos/<int:proceso_id>/bitacora/',
        views_extra.proceso_bitacora_view,
        name='proceso_bitacora',
    ),
    path(
        'procesos/<int:proceso_id>/aplicaciones-publicas/',
        views_extra.proceso_aplicaciones_publicas_view,
        name='proceso_aplicaciones_publicas',
    ),
    path(
        'procesos/<int:proceso_id>/participantes/nuevo/',
        views.participante_crear_view,
        name='participante_crear',
    ),
    path(
        'procesos/<int:proceso_id>/configuracion/',
        views.configuracion_view,
        name='configuracion',
    ),
    path(
        'procesos/<int:proceso_id>/aplicacion-publica/generar/',
        views.aplicacion_publica_proceso_generar_view,
        name='aplicacion_publica_proceso_generar',
    ),
    path(
        'procesos/<int:proceso_id>/aplicacion-publica/estado/',
        views.aplicacion_publica_proceso_estado_view,
        name='aplicacion_publica_proceso_estado',
    ),
    path(
        'procesos/<int:proceso_id>/aplicacion-publica/codigo-qr.svg',
        views.aplicacion_publica_proceso_qr_view,
        name='aplicacion_publica_proceso_qr',
    ),
    path(
        'participantes/<int:participante_id>/',
        views.participante_detalle_view,
        name='participante_detalle',
    ),
    path(
        'participantes/<int:participante_id>/editar/',
        views.participante_editar_view,
        name='participante_editar',
    ),
    path(
        'participantes/<int:participante_id>/eliminar/',
        views.participante_eliminar_view,
        name='participante_eliminar',
    ),
    path(
        'participantes/<int:participante_id>/aplicaciones/nueva/',
        views.aplicacion_crear_view,
        name='aplicacion_crear',
    ),
    path(
        'participantes/<int:participante_id>/entrevista/',
        views.entrevista_crear_view,
        name='entrevista_crear',
    ),
    path(
        'participantes/<int:participante_id>/consejerias/nueva/',
        views.consejeria_crear_view,
        name='consejeria_crear',
    ),
    path(
        'participantes/<int:participante_id>/canalizaciones/nueva/',
        views_extra.canalizacion_crear_view,
        name='canalizacion_crear',
    ),
    path(
        'canalizaciones/<int:canalizacion_id>/',
        views_extra.canalizacion_detalle_view,
        name='canalizacion_detalle',
    ),
    path(
        'canalizaciones/<int:canalizacion_id>/editar/',
        views_extra.canalizacion_editar_view,
        name='canalizacion_editar',
    ),
    path(
        'participantes/<int:participante_id>/entrevista-1a1/acceso/',
        views_entrevista_1a1.acceso_view,
        name='entrevista_1a1_acceso',
    ),
    path(
        'participantes/<int:participante_id>/entrevista-1a1/',
        views_entrevista_1a1.entrevista_view,
        name='entrevista_1a1',
    ),
    path(
        'participantes/<int:participante_id>/entrevista-1a1/reabrir/',
        views_entrevista_1a1.reabrir_view,
        name='entrevista_1a1_reabrir',
    ),
    path(
        'canalizaciones/<int:canalizacion_id>/confirmar-envio-consultorio/',
        views_extra.solicitud_confirmar_envio_view,
        name='solicitud_confirmar_envio',
    ),
    path(
        'canalizaciones/<int:canalizacion_id>/enviar-consultorio/',
        views_extra.solicitud_enviar_view,
        name='solicitud_enviar',
    ),
    path(
        'canalizaciones/<int:canalizacion_id>/actualizar-estado-consultorio/',
        views_extra.solicitud_actualizar_estado_view,
        name='solicitud_actualizar_estado',
    ),
    path(
        'aplicaciones/<int:aplicacion_id>/resultado/',
        views.resultado_view,
        name='resultado',
    ),
    path(
        'aplicar/<uuid:token>/',
        views.aplicacion_publica_config_view,
        name='aplicacion_publica',
    ),
    path(
        'aplicaciones-individuales/<uuid:token>/',
        views.aplicacion_publica_view,
        name='aplicacion_individual',
    ),
]
