# Generated by Django 5.2.10 on 2026-07-08 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donante_nombre', models.CharField(max_length=200)),
                ('donante_rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('tipo', models.CharField(choices=[('monetario', 'Monetario'), ('especie', 'En especie')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('folio_cfdi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio CFDI')),
                ('estatus_cfdi', models.CharField(choices=[('vigente', 'Vigente'), ('cancelado', 'Cancelado'), ('tramite', 'En trámite')], default='tramite', max_length=10, verbose_name='Estatus CFDI')),
                ('archivo_xml', models.FileField(blank=True, null=True, upload_to='finanzas/donativos/xml/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='finanzas/donativos/pdf/')),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Donativo',
                'verbose_name_plural': 'Donativos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('renta', 'Renta'), ('servicios', 'Servicios'), ('insumos', 'Insumos'), ('nomina_admin', 'Nómina administrativa')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Tabulador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('A', 'Categoría A'), ('B', 'Categoría B'), ('C', 'Categoría C')], max_length=1)),
                ('pago_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('umbral_pacientes_semana', models.PositiveIntegerField(help_text='Número de pacientes atendidos por semana a partir del cual aplica el bono de gasolina.')),
                ('monto_bono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigente_desde', models.DateField()),
            ],
            options={
                'verbose_name': 'Tabulador',
                'verbose_name_plural': 'Tabuladores',
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('consulta', 'Consulta'), ('inscripcion_diplomado', 'Inscripción diplomado'), ('mensualidad_diplomado', 'Mensualidad diplomado'), ('inscripcion_taller', 'Inscripción taller'), ('mensualidad_taller', 'Mensualidad taller'), ('curso_certificacion', 'Curso / certificación')], max_length=30)),
                ('persona', models.CharField(blank=True, max_length=150, verbose_name='Alumno / Paciente')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estatus', models.CharField(choices=[('pagado', 'Pagado'), ('parcial', 'Parcial'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10)),
                ('fecha', models.DateField()),
                ('terapeuta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Honorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_mes', models.PositiveSmallIntegerField()),
                ('periodo_anio', models.PositiveSmallIntegerField()),
                ('num_pacientes', models.PositiveIntegerField()),
                ('bono', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('estatus', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10)),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='honorarios', to=settings.AUTH_USER_MODEL)),
                ('tabulador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='honorarios', to='finanzas.tabulador')),
            ],
            options={
                'verbose_name': 'Honorario',
                'verbose_name_plural': 'Honorarios',
                'ordering': ['-periodo_anio', '-periodo_mes'],
                'unique_together': {('terapeuta', 'periodo_mes', 'periodo_anio')},
            },
        ),
    ]
