# Generated by Django 5.2.10 on 2026-07-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_grupo_finanzas'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='estatus',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], default='pagado', max_length=10),
        ),
        migrations.AddField(
            model_name='egreso',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AddField(
            model_name='egreso',
            name='persona',
            field=models.CharField(blank=True, max_length=150, verbose_name='Terapeuta / Proveedor'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='referencia_externa',
            field=models.CharField(blank=True, editable=False, max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='categoria',
            field=models.CharField(choices=[('renta', 'Renta'), ('servicios', 'Servicios'), ('insumos', 'Insumos'), ('nomina_admin', 'Nómina administrativa'), ('nomina_terapeutas', 'Nómina terapeutas (ConsultorioWeb)')], max_length=20),
        ),
    ]
