# Generated by Django 5.2.10 on 2026-07-21 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_egreso_nomina_semanal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_cita', models.CharField(blank=True, max_length=50)),
                ('paciente', models.CharField(max_length=150)),
                ('terapeuta', models.CharField(max_length=150)),
                ('servicio', models.CharField(blank=True, max_length=100)),
                ('division', models.CharField(blank=True, max_length=100, verbose_name='División')),
                ('consultorio', models.CharField(blank=True, max_length=100)),
                ('estatus', models.CharField(choices=[('confirmada', 'Confirmada'), ('sin_confirmar', 'Sin confirmar'), ('reagendo', 'Reagendó'), ('cancelo', 'Canceló'), ('si_asistio', 'Sí asistió'), ('no_asistio', 'No asistió'), ('incidencia', 'Incidencia')], max_length=20)),
                ('metodo_pago', models.CharField(blank=True, choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('pase', 'Pase'), ('debito', 'Débito'), ('credito', 'Crédito')], max_length=20)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ingreso', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita_recepcion', to='finanzas.ingreso')),
            ],
            options={
                'verbose_name': 'Cita de Recepción',
                'verbose_name_plural': 'Citas de Recepción',
                'ordering': ['-fecha', '-hora'],
                'unique_together': {('fecha', 'hora', 'paciente', 'terapeuta', 'servicio')},
            },
        ),
    ]
