# Generated by Django 5.2.10 on 2026-07-21 17:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_citarecepcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Maestro (Academia)',
                'verbose_name_plural': 'Maestros (Academia)',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TabuladorAcademia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('horas_clase', 'Horas clase'), ('supervision', 'Supervisión'), ('mesa_trabajo', 'Mesa de trabajo')], max_length=20)),
                ('monto_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigente_desde', models.DateField()),
            ],
            options={
                'verbose_name': 'Tabulador de Academia',
                'verbose_name_plural': 'Tabuladores de Academia',
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.AlterField(
            model_name='egreso',
            name='categoria',
            field=models.CharField(choices=[('renta', 'Renta'), ('servicios', 'Servicios'), ('insumos', 'Insumos'), ('nomina_admin', 'Nómina administrativa'), ('nomina_terapeutas', 'Nómina terapeutas (ConsultorioWeb)'), ('nomina_academia', 'Nómina Academia')], max_length=20),
        ),
        migrations.CreateModel(
            name='NominaAcademia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_mes', models.PositiveSmallIntegerField()),
                ('periodo_anio', models.PositiveSmallIntegerField()),
                ('metodo_pago', models.CharField(blank=True, choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo')], max_length=20)),
                ('estatus', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10)),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominas', to='finanzas.maestro')),
            ],
            options={
                'verbose_name': 'Nómina Academia',
                'verbose_name_plural': 'Nóminas Academia',
                'ordering': ['-periodo_anio', '-periodo_mes'],
                'unique_together': {('maestro', 'periodo_mes', 'periodo_anio')},
            },
        ),
        migrations.CreateModel(
            name='ConceptoNominaAcademia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('horas_clase', 'Horas clase'), ('supervision', 'Supervisión'), ('mesa_trabajo', 'Mesa de trabajo'), ('manual', 'Concepto manual autorizado')], max_length=20)),
                ('descripcion', models.CharField(blank=True, help_text='Solo para el concepto manual autorizado.', max_length=150)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=6)),
                ('tarifa', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='finanzas.nominaacademia')),
                ('tabulador', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_generados', to='finanzas.tabuladoracademia')),
            ],
            options={
                'verbose_name': 'Concepto de Nómina Academia',
                'verbose_name_plural': 'Conceptos de Nómina Academia',
            },
        ),
    ]
