# Generated by Django 5.2.10 on 2026-07-21 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('finanzas', '0005_maestro_tabuladoracademia_alter_egreso_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('motivo', models.CharField(max_length=255)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'finanzas'), ('model__in', ('honorario', 'nominaacademia', 'egreso'))), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('egreso_generado', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajuste_origen', to='finanzas.egreso')),
            ],
            options={
                'verbose_name': 'Ajuste',
                'verbose_name_plural': 'Ajustes',
                'ordering': ['-creado_en'],
            },
        ),
    ]
