# Generated by Django 5.2.10 on 2026-07-21 18:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_ajuste'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Egreso (adicional)',
                'verbose_name_plural': 'Categorías de Egreso (adicionales)',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Concepto de Ingreso (adicional)',
                'verbose_name_plural': 'Conceptos de Ingreso (adicionales)',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='ingreso',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='categoria',
            field=models.CharField(choices=[('renta', 'Renta'), ('servicios', 'Servicios'), ('insumos', 'Insumos'), ('nomina_admin', 'Nómina administrativa'), ('nomina_terapeutas', 'Nómina terapeutas (ConsultorioWeb)'), ('nomina_academia', 'Nómina Academia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='concepto',
            field=models.CharField(choices=[('consulta', 'Consulta'), ('inscripcion_diplomado', 'Inscripción diplomado'), ('mensualidad_diplomado', 'Mensualidad diplomado'), ('inscripcion_taller', 'Inscripción taller'), ('mensualidad_taller', 'Mensualidad taller'), ('curso_certificacion', 'Curso / certificación')], max_length=50),
        ),
    ]
