# Generated by Django 5.2.10 on 2026-09-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0013_egreso_unidad_ingreso_unidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maestro',
            options={'ordering': ['nombre'], 'verbose_name': 'Persona (Academia)', 'verbose_name_plural': 'Personas (Academia)'},
        ),
        migrations.AddField(
            model_name='maestro',
            name='tipo',
            field=models.CharField(choices=[('maestro', 'Maestro'), ('administrativo', 'Administrativo')], default='maestro', max_length=20),
        ),
    ]
